<wsdl:definitions
     name="deQueueMessage"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/aq/proj-Fusion12c/dequeueAQ/deQueueMessage"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/aq/proj-Fusion12c/dequeueAQ/deQueueMessage"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:pc="http://xmlns.oracle.com/pcbpel/"
     xmlns:obj1="http://xmlns.oracle.com/xdb/SHOP_KEEPER"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="Dequeue_plt" >
    <plt:role name="Dequeue_role" >
      <plt:portType name="tns:Dequeue_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/xdb/SHOP_KEEPER" schemaLocation="../Schemas/SHOP_KEEPER_ITEM_TYPE.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="ITEM_TYPE_msg">
        <wsdl:part name="ITEM_TYPE" element="obj1:ITEM_TYPE"/>
    </wsdl:message>
    <wsdl:portType name="Dequeue_ptt">
        <wsdl:operation name="Dequeue">
            <wsdl:input message="tns:ITEM_TYPE_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
